In [2]:
data = """
Hubble has taken many images of nebuals - beautiful stellar creations.
Although this is not Hubble’s first image of this iconic feature of the Eagle Nebula,
it is the most detailed. The blue colors in the image represent oxygen,
red is sulfur, and green represents both nitrogen and hydrogen.
The pillars are bathed in the scorching ultraviolet light from a cluster of young stars located just outside the frame.
The winds from these stars are slowly eroding the towers of gas and dust.
Stretching roughly 4 to 5 light-years,
the Pillars of Creation are a fascinating but relatively small feature of the entire Eagle Nebula,
which spans 70 by 55 light-years.
The nebula, discovered in 1745 by the Swiss astronomer Jean-Philippe Loys de Chéseaux,
it is located 7,000 light-years from Earth in the constellation Serpens.
With an apparent magnitude of 6,
the star cluster in the Eagle Nebula can be spotted through a small telescope and is best viewed during August.
However, a large telescope and optimal viewing conditions are necessary
to resolve the Pillars of Creation within the nebula.
These towering tendrils of cosmic dust and gas sit at the heart of Messier 16, or the Eagle Nebula.
The aptly named Pillars of Creation,
featured in this stunning Hubble image, are part of an active star-forming region
within the nebula and hide newborn stars in their wispy columns.
M16 is the collective name for two distinct objects
that are listed separately in astronomical catalogues
an emission nebula, referred to as IC 4703,
and an open star cluster, designated as NGC 6611.
"""

In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [4]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
print("Done Tokenizing")

Done Tokenizing


In [5]:
len(tokenizer.word_index)
tokenizer.word_counts

OrderedDict([('hubble', 2),
             ('has', 1),
             ('taken', 1),
             ('many', 1),
             ('images', 1),
             ('of', 13),
             ('nebuals', 1),
             ('beautiful', 1),
             ('stellar', 1),
             ('creations', 1),
             ('although', 1),
             ('this', 3),
             ('is', 6),
             ('not', 1),
             ('hubble’s', 1),
             ('first', 1),
             ('image', 3),
             ('iconic', 1),
             ('feature', 2),
             ('the', 23),
             ('eagle', 4),
             ('nebula', 8),
             ('it', 2),
             ('most', 1),
             ('detailed', 1),
             ('blue', 1),
             ('colors', 1),
             ('in', 8),
             ('represent', 1),
             ('oxygen', 1),
             ('red', 1),
             ('sulfur', 1),
             ('and', 8),
             ('green', 1),
             ('represents', 1),
             ('both', 1),
             (

In [6]:
for sentence in data.split('\n'):
  print(sentence)


Hubble has taken many images of nebuals - beautiful stellar creations.
Although this is not Hubble’s first image of this iconic feature of the Eagle Nebula,
it is the most detailed. The blue colors in the image represent oxygen,
red is sulfur, and green represents both nitrogen and hydrogen.
The pillars are bathed in the scorching ultraviolet light from a cluster of young stars located just outside the frame.
The winds from these stars are slowly eroding the towers of gas and dust.
Stretching roughly 4 to 5 light-years,
the Pillars of Creation are a fascinating but relatively small feature of the entire Eagle Nebula,
which spans 70 by 55 light-years.
The nebula, discovered in 1745 by the Swiss astronomer Jean-Philippe Loys de Chéseaux,
it is located 7,000 light-years from Earth in the constellation Serpens.
With an apparent magnitude of 6,
the star cluster in the Eagle Nebula can be spotted through a small telescope and is best viewed during August.
However, a large telescope and opti

In [7]:
for sent in data.split("\n"):
  print(tokenizer.texts_to_sequences([sent])[0])

[]
[22, 34, 35, 36, 37, 2, 38, 39, 40, 41]
[42, 13, 6, 43, 44, 45, 14, 2, 13, 46, 23, 2, 1, 8, 3]
[24, 6, 1, 47, 48, 1, 49, 50, 4, 1, 14, 51, 52]
[53, 6, 54, 5, 55, 56, 57, 58, 5, 59]
[1, 9, 7, 60, 4, 1, 61, 62, 10, 15, 11, 16, 2, 63, 17, 25, 64, 65, 1, 66]
[1, 67, 15, 26, 17, 7, 68, 69, 1, 70, 2, 27, 5, 28]
[71, 72, 73, 18, 74, 10, 19]
[1, 9, 2, 20, 7, 11, 75, 76, 77, 29, 23, 2, 1, 78, 8, 3]
[79, 80, 81, 30, 82, 10, 19]
[1, 3, 83, 4, 84, 30, 1, 85, 86, 87, 88, 89, 90, 91]
[24, 6, 25, 92, 93, 10, 19, 15, 94, 4, 1, 95, 96]
[97, 12, 98, 99, 2, 100]
[1, 21, 16, 4, 1, 8, 3, 101, 102, 103, 104, 11, 29, 31, 5, 6, 105, 106, 107, 108]
[109, 11, 110, 31, 5, 111, 112, 113, 7, 114]
[18, 115, 1, 9, 2, 20, 32, 1, 3]
[26, 116, 117, 2, 118, 28, 5, 27, 119, 120, 1, 121, 2, 122, 123, 124, 1, 8, 3]
[1, 125, 126, 9, 2, 20]
[127, 4, 13, 128, 22, 14, 7, 129, 2, 12, 130, 21, 131, 132]
[32, 1, 3, 5, 133, 134, 17, 4, 135, 136, 137]
[138, 6, 1, 139, 140, 141, 142, 143, 144]
[145, 7, 146, 147, 4, 148, 149]
[12,

In [8]:
input = []
for sent in data.split("\n"):
  tokenized_data = tokenizer.texts_to_sequences([sent])[0]

  for i in range(1,len(tokenized_data)):
    input.append(tokenized_data[:i+1])

# input
# Apply padding , find the maximum length of sequences
max_len = max([len(x) for x in input])
max_len

20

In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_input_sequences = pad_sequences(input,maxlen = max_len,padding = 'pre')
padded_input_sequences

array([[  0,   0,   0, ...,   0,  22,  34],
       [  0,   0,   0, ...,  22,  34,  35],
       [  0,   0,   0, ...,  34,  35,  36],
       ...,
       [  0,   0,   0, ...,  16, 155,  33],
       [  0,   0,   0, ..., 155,  33, 156],
       [  0,   0,   0, ...,  33, 156, 157]], dtype=int32)

In [10]:
# Creating our X,Y
X = padded_input_sequences[:,:-1] # All rows and all columns till the last (excluding last)
y = padded_input_sequences[:,-1] # All rows adn just the last column

In [11]:
X

array([[  0,   0,   0, ...,   0,   0,  22],
       [  0,   0,   0, ...,   0,  22,  34],
       [  0,   0,   0, ...,  22,  34,  35],
       ...,
       [  0,   0,   0, ...,  21,  16, 155],
       [  0,   0,   0, ...,  16, 155,  33],
       [  0,   0,   0, ..., 155,  33, 156]], dtype=int32)

In [12]:
y

array([ 34,  35,  36,  37,   2,  38,  39,  40,  41,  13,   6,  43,  44,
        45,  14,   2,  13,  46,  23,   2,   1,   8,   3,   6,   1,  47,
        48,   1,  49,  50,   4,   1,  14,  51,  52,   6,  54,   5,  55,
        56,  57,  58,   5,  59,   9,   7,  60,   4,   1,  61,  62,  10,
        15,  11,  16,   2,  63,  17,  25,  64,  65,   1,  66,  67,  15,
        26,  17,   7,  68,  69,   1,  70,   2,  27,   5,  28,  72,  73,
        18,  74,  10,  19,   9,   2,  20,   7,  11,  75,  76,  77,  29,
        23,   2,   1,  78,   8,   3,  80,  81,  30,  82,  10,  19,   3,
        83,   4,  84,  30,   1,  85,  86,  87,  88,  89,  90,  91,   6,
        25,  92,  93,  10,  19,  15,  94,   4,   1,  95,  96,  12,  98,
        99,   2, 100,  21,  16,   4,   1,   8,   3, 101, 102, 103, 104,
        11,  29,  31,   5,   6, 105, 106, 107, 108,  11, 110,  31,   5,
       111, 112, 113,   7, 114, 115,   1,   9,   2,  20,  32,   1,   3,
       116, 117,   2, 118,  28,   5,  27, 119, 120,   1, 121,   

In [13]:
X.shape

(244, 19)

In [14]:
y.shape

(244,)

In [15]:
len(tokenizer.word_index)

157

In [16]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=158) # 1 extra because out vacab starts assigning index from 1, so this would essentially miss encoding last value of vocab as size starts from 0-->157 ....
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [18]:
model = Sequential()
model.add(Embedding(158,100,input_length=max_len-1))
model.add(LSTM(150))
model.add(Dense(158,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.fit(X,y,epochs=300)

Epoch 1/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 4s 66ms/step - accuracy: 0.0283 - loss: 5.0605
Epoch 2/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.0750 - loss: 4.9963
Epoch 3/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.0873 - loss: 4.7207
Epoch 4/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.0832 - loss: 4.7332
Epoch 5/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.0806 - loss: 4.6738
Epoch 6/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.0702 - loss: 4.5974
Epoch 7/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.0725 - loss: 4.5609
Epoch 8/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.0706 - loss: 4.5379
Epoch 9/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.0958 - loss: 4.4464
Epoch 10/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.1084 - loss: 4.3365
Epoch 11/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.0903 - loss: 4.3130
Epoch 12/300
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.1147 - lo

In [22]:
import numpy as np

In [28]:
test = "nebula"

for i in range(10):
  # Tokenize
  token_test = tokenizer.texts_to_sequences([test])[0]
  # Pad
  padded_token_test = pad_sequences([token_test],max_len-1,padding='pre')
  # Predict
  model.predict(padded_token_test)
  position = np.argmax(model.predict(padded_token_test))

  for word,index in tokenizer.word_index.items():
    if index == position:
      test = test + " " + word

  print(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
nebula discovered
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
nebula discovered in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
nebula discovered in 1745
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
nebula discovered in 1745 by
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
nebula discovered in 1745 by the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
nebula discovered in 1745 by the swiss
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
nebula discovered in 1745 by the swiss astronomer
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
nebula discovered in 1745 by the swiss astronomer jean
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
nebula discovered in 1745 by the swiss astron